version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: loop_postgres
    environment:
      POSTGRES_DB: loop_db
      POSTGRES_USER: loop_user
      POSTGRES_PASSWORD: loop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loop_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: loop_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - loop_network

networks:
  loop_network:

volumes:
  postgres_data: