# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-08-31 10:08
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ping.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(unique=True, upload_to=ping.helpers.generate_file_path, validators=[django.core.validators.FileExtensionValidator([b'csv'])])),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default=b'America/Chicago', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBusinessHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')])),
                ('start_time_local', models.TimeField(default=datetime.time(0, 0))),
                ('end_time_local', models.TimeField(default=datetime.time(23, 59))),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_hours', to='ping.Store')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls', to='ping.Store'),
        ),
    ]
