# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-09-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_auto_20240831_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='storebusinesshour',
            index=models.Index(fields=[b'store', b'day_of_week'], name='ping_storeb_store_i_b1301b_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=[b'timestamp'], name='ping_poll_timesta_df64eb_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=[b'store', b'timestamp'], name='ping_poll_store_i_5fe6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=[b'timezone'], name='ping_store_timezon_571aad_idx'),
        ),
    ]
